### ISSUE TITLE
Disable default provider suggesting words originated in comments

### ISSUE THREAD

**Issue by eyalw** [atom/autocomplete-plus#619]
See example below, I am offered a list of plain words that appear in comments around my code instead of only symbols (variables, functions, keywords).
I want to use the default provider symbols options, but without this mess.
is this possible?

![screen shot 2015-11-19 at 2 48 06 pm](https://cloud.githubusercontent.com/assets/608669/11271109/900a23b4-8ecc-11e5-9d04-e66eb922a446.png)

**Comment by benogle** [comment]
Dupe of https://github.com/atom/autocomplete-plus/issues/377

**Comment by eyalw** [comment]
@benogle This is not a duplicate of #377 , 
#377 is talking about disabling completion in comments (while in comment, don't complete me)
I'm talking about disabling completion of words originated in comments (while in code, don't offer to complete me with words from comments)
basically just show me variable and function names.
please consider reopening this :)

**Comment by benogle** [comment]
You should be able to change the default config for the symbol provider. Add this to your config under `*`. 

```
  autocomplete:
    symbols:
      class:
        selector: '.class.name, .inherited-class, .instance.type'
        typePriority: 4
      function:
        selector: '.function.name'
        typePriority: 3
      variable:
        selector: '.variable'
        typePriority: 2
```

You can also set it up for specific languages as well by scoping it to your grammar of choice.
