### ISSUE TITLE
How to increase width of rightLabel.

### ISSUE THREAD

**Issue by jordwalke** [atom/autocomplete-plus#670]
![screen shot 2016-02-10 at 1 30 19 am](https://cloud.githubusercontent.com/assets/977348/12943545/d7b42466-cf96-11e5-9ffc-0b671d8e601e.png)

The right label should make better use of the available space. In fact, I would say that even if there wasn't a description (shown in the lowest portion), it should be possible to make the entire popup resize to make room for the longest right label (up to some max-width setting).

In the screenshot, I'm showing the type system types in the right hand column, but the type is truncated to the point of being useless.

**Comment by aemxdp** [comment]
+1

**Comment by n0o0bSina** [comment]
:+1:

**Comment by designorant** [comment]
A quick workaround would be to play with the `min/max-width` values in the following snippet, and paste the whole thing into `styles.less`:
```less
autocomplete-suggestion-list.select-list.popover-list {
  min-width: 200px;
  max-width: 800px;
}

autocomplete-suggestion-list {

  .left-label {
    max-width: 150px;
  }

  .right-label {
    max-width: 250px; // 150px by default
  }

  .word {
    max-width: 400px; // 500px by default
  }

}
```

Long term wise, there might be some changes that will fix this behaviour as there is a PR that somewhat relates to this. See issue #728, and PR #729.
