### ISSUE TITLE
Much blinking near the end of file

### ISSUE THREAD

**Issue by DatName** [atom/autocomplete-plus#680]
When typing near the end of file (for example, line 85 out of total 90) dropdown menu blinks, trying to figure out best position for itself: either above or below selected line. After some time (about second or less) it stops doing that, but if I type, for example, "for" and move cursor away from the atom application window it keeps blinking until I move cursor back.

**Comment by jasongilman** [comment]
I've seen this a lot in my own development and with other people I'm working with. We're mostly doing completion in Clojure files with documentation included in the window.  The problem is exactly as described. It tries to position it below the cursor, then switches above and then back below. It will flash between those two states. I can't reproduce it consistently so it seems to rely on having the right set of circumstances. 

Autocomplete plus is just using an overlay so it's more likely a bug in the Atom overlay layout code.
I have a hunch problem might be somewhere in text-editor-presenter.coffee updateOverlaysState.

**Comment by jordwalke** [comment]
Any word on the general flakiness/jumpiness of autocomplete-plus? It makes Atom feel kind of cheap, so I think making autocomplete-plus solid and reliable is high impact for Atom.

**Comment by p2kmgcl** [comment]
Until a real fix comes, if have created this stylesheet quick fix which works really well:

```less
atom-overlay.autocomplete-plus {
  // Although this creates a nice animation, it makes the popup
  // come from the bottom of the file everytime it appears, so
  // I would keep it disabled.
  // transition: top ease 0.3s, left ease 0.3s;
}

autocomplete-suggestion-list.select-list.popover-list {
  // This animation is toggled everytime the left column
  // which specifies if the completion is a variable, function,
  // or anything else appears/dissappears.
  transition: margin-left ease 0.3s;

  // Giving a fixed with to the completion popup
  // prevents from flickering during different suggestions
  min-width: 400px;
  max-width: 400px;

  // Giving a fixed height to the popup prevents from
  // moving up and down when we are typing at the
  // bottom of the file. For some reason it won't grow
  // more than 350px in my editor, so consider this the
  // maximum value.
  min-height: 350px;
  max-height: 350px;

  // This position pulls down the description completion
  // (for example for css properties).
  & > .suggestion-description {
    position: absolute;
    bottom: 0;
    width: 100%;
  }
}
```

I know it is just a silly patch, but it works perfectly in my editor :cat:
