### ISSUE TITLE
Request: customizable suggestion window width preference

### ISSUE THREAD

**Issue by emveeoh** [atom/autocomplete-plus#694]
It would be nice to have the ability to customize the width of the suggestion window. The default setting is  too thin. Sometimes, it is difficult to tell what the autocomplete command is for as the text is truncated too much. Additional width on the suggestion box would be helpful.

Thank you!
:)

**Comment by joefitzgerald** [comment]
I agree with this. The suggestion window should be a bit more greedy about space, when available - particularly when suggestions would be truncated.

**Comment by simurai** [comment]
You can paste the following into your `styles.less` and then try to tweak the numbers.

```less
autocomplete-suggestion-list {
  &.select-list.popover-list {
    max-width: none;
    width: auto !important;
  }
  .left-label { max-width: 300px; }
  .word { max-width: 500px; } // 500px by default
  .right-label { max-width: 500px; } // 150px by default 
}
```

The width of the columns depends on the language used.
