### ISSUE TITLE
settings by scope descriptior

### ISSUE THREAD

**Issue by joeroback** [atom/autocomplete-plus#749]
I am trying to set settings via scope in config.cson, but it doesn't look like autocomplete-plus uses scope open to config.get...

```
".cpp.source":
  "autocomplete-plus":
    maxVisibleSuggestions: 8
  editor:
    preferredLineLength: 120
    tabLength: 4
  linter:
    showErrorInline: false
```

For certain languages I would to be able to change things like maxVisibleSuggestions. Am I just missing something and being an idiot or is this not supported?
